# https://www.home-assistant.io/components/logbook/

# Note: All entries need to also be defined in recorder.yaml

include:
  domains: 
    - device_tracker
    - automation
  entities:
    # Travis CI
    - sensor.shortblokehome_assistant_config_last_build_state
    - sensor.shortblokehome_assistant_config_last_build_id
    # Nest
    - binary_sensor.northway_away